-- GENERADO POR scripts/build-seed.mjs — no editar a mano.
-- Editar supabase/seed/catalog.mjs y ejecutar `npm run seed:build`.

begin;

-- Juegos ------------------------------------------------------------------
insert into public.games (slug, name, release_year) values
  ('fc27', 'EA SPORTS FC 27', 2026),
  ('fc26', 'EA SPORTS FC 26', 2025)
on conflict (slug) do update
  set name = excluded.name, release_year = excluded.release_year;

-- Sliders -----------------------------------------------------------------
insert into public.slider_definitions
  (game_id, category, applies_to, name, slug, min_value, max_value, default_value, sort_order)
values
  ((select id from public.games where slug = 'fc27'), 'speed', 'user', 'Velocidad', 'sprint_speed', 1, 99, 50, 0),
  ((select id from public.games where slug = 'fc27'), 'speed', 'cpu_opponent', 'Velocidad', 'sprint_speed', 1, 99, 50, 0),
  ((select id from public.games where slug = 'fc27'), 'speed', 'user', 'Aceleración', 'acceleration', 1, 99, 50, 10),
  ((select id from public.games where slug = 'fc27'), 'speed', 'cpu_opponent', 'Aceleración', 'acceleration', 1, 99, 50, 10),
  ((select id from public.games where slug = 'fc27'), 'shooting', 'user', 'Fallo al tirar', 'shot_error', 1, 99, 50, 20),
  ((select id from public.games where slug = 'fc27'), 'shooting', 'cpu_opponent', 'Fallo al tirar', 'shot_error', 1, 99, 50, 20),
  ((select id from public.games where slug = 'fc27'), 'shooting', 'user', 'Velocidad de tiro', 'shot_speed', 1, 99, 50, 30),
  ((select id from public.games where slug = 'fc27'), 'shooting', 'cpu_opponent', 'Velocidad de tiro', 'shot_speed', 1, 99, 50, 30),
  ((select id from public.games where slug = 'fc27'), 'shooting', 'user', 'Fallo en tiro colocado', 'finesse_shot_error', 1, 99, 50, 40),
  ((select id from public.games where slug = 'fc27'), 'shooting', 'cpu_opponent', 'Fallo en tiro colocado', 'finesse_shot_error', 1, 99, 50, 40),
  ((select id from public.games where slug = 'fc27'), 'shooting', 'user', 'Velocidad de tiro colocado', 'finesse_shot_speed', 1, 99, 50, 50),
  ((select id from public.games where slug = 'fc27'), 'shooting', 'cpu_opponent', 'Velocidad de tiro colocado', 'finesse_shot_speed', 1, 99, 50, 50),
  ((select id from public.games where slug = 'fc27'), 'shooting', 'user', 'Fallo en tiro por elevación', 'chip_shot_error', 1, 99, 50, 60),
  ((select id from public.games where slug = 'fc27'), 'shooting', 'cpu_opponent', 'Fallo en tiro por elevación', 'chip_shot_error', 1, 99, 50, 60),
  ((select id from public.games where slug = 'fc27'), 'shooting', 'user', 'Velocidad de tiro por elevación', 'chip_shot_speed', 1, 99, 50, 70),
  ((select id from public.games where slug = 'fc27'), 'shooting', 'cpu_opponent', 'Velocidad de tiro por elevación', 'chip_shot_speed', 1, 99, 50, 70),
  ((select id from public.games where slug = 'fc27'), 'shooting', 'user', 'Fallo en tiro raso', 'low_driven_shot_error', 1, 99, 50, 80),
  ((select id from public.games where slug = 'fc27'), 'shooting', 'cpu_opponent', 'Fallo en tiro raso', 'low_driven_shot_error', 1, 99, 50, 80),
  ((select id from public.games where slug = 'fc27'), 'shooting', 'user', 'Velocidad de tiro raso', 'low_driven_shot_speed', 1, 99, 50, 90),
  ((select id from public.games where slug = 'fc27'), 'shooting', 'cpu_opponent', 'Velocidad de tiro raso', 'low_driven_shot_speed', 1, 99, 50, 90),
  ((select id from public.games where slug = 'fc27'), 'shooting', 'user', 'Fallo en disparo potente', 'power_shot_error', 1, 99, 50, 100),
  ((select id from public.games where slug = 'fc27'), 'shooting', 'cpu_opponent', 'Fallo en disparo potente', 'power_shot_error', 1, 99, 50, 100),
  ((select id from public.games where slug = 'fc27'), 'shooting', 'user', 'Velocidad de disparo potente', 'power_shot_speed', 1, 99, 50, 110),
  ((select id from public.games where slug = 'fc27'), 'shooting', 'cpu_opponent', 'Velocidad de disparo potente', 'power_shot_speed', 1, 99, 50, 110),
  ((select id from public.games where slug = 'fc27'), 'shooting', 'user', 'Fallo al rematar de cabeza', 'header_shot_error', 1, 99, 50, 120),
  ((select id from public.games where slug = 'fc27'), 'shooting', 'cpu_opponent', 'Fallo al rematar de cabeza', 'header_shot_error', 1, 99, 50, 120),
  ((select id from public.games where slug = 'fc27'), 'passing', 'user', 'Fallo al pasar', 'pass_error', 1, 99, 50, 130),
  ((select id from public.games where slug = 'fc27'), 'passing', 'cpu_opponent', 'Fallo al pasar', 'pass_error', 1, 99, 50, 130),
  ((select id from public.games where slug = 'fc27'), 'passing', 'user', 'Velocidad del pase', 'pass_speed', 1, 99, 50, 140),
  ((select id from public.games where slug = 'fc27'), 'passing', 'cpu_opponent', 'Velocidad del pase', 'pass_speed', 1, 99, 50, 140),
  ((select id from public.games where slug = 'fc27'), 'passing', 'user', 'Fallo al pasar de cabeza', 'header_pass_error', 1, 99, 50, 150),
  ((select id from public.games where slug = 'fc27'), 'passing', 'cpu_opponent', 'Fallo al pasar de cabeza', 'header_pass_error', 1, 99, 50, 150),
  ((select id from public.games where slug = 'fc27'), 'passing', 'user', 'Fallo en pase al hueco', 'through_pass_error', 1, 99, 50, 160),
  ((select id from public.games where slug = 'fc27'), 'passing', 'cpu_opponent', 'Fallo en pase al hueco', 'through_pass_error', 1, 99, 50, 160),
  ((select id from public.games where slug = 'fc27'), 'passing', 'user', 'Velocidad de pase al hueco', 'through_pass_speed', 1, 99, 50, 170),
  ((select id from public.games where slug = 'fc27'), 'passing', 'cpu_opponent', 'Velocidad de pase al hueco', 'through_pass_speed', 1, 99, 50, 170),
  ((select id from public.games where slug = 'fc27'), 'passing', 'user', 'Fallo en pase bombeado al hueco', 'lobbed_through_pass_error', 1, 99, 50, 180),
  ((select id from public.games where slug = 'fc27'), 'passing', 'cpu_opponent', 'Fallo en pase bombeado al hueco', 'lobbed_through_pass_error', 1, 99, 50, 180),
  ((select id from public.games where slug = 'fc27'), 'passing', 'user', 'Velocidad de pase bombeado al hueco', 'lobbed_through_pass_speed', 1, 99, 50, 190),
  ((select id from public.games where slug = 'fc27'), 'passing', 'cpu_opponent', 'Velocidad de pase bombeado al hueco', 'lobbed_through_pass_speed', 1, 99, 50, 190),
  ((select id from public.games where slug = 'fc27'), 'passing', 'user', 'Fallo en pase en globo', 'lob_pass_error', 1, 99, 50, 200),
  ((select id from public.games where slug = 'fc27'), 'passing', 'cpu_opponent', 'Fallo en pase en globo', 'lob_pass_error', 1, 99, 50, 200),
  ((select id from public.games where slug = 'fc27'), 'passing', 'user', 'Velocidad de pase en globo', 'lob_pass_speed', 1, 99, 50, 210),
  ((select id from public.games where slug = 'fc27'), 'passing', 'cpu_opponent', 'Velocidad de pase en globo', 'lob_pass_speed', 1, 99, 50, 210),
  ((select id from public.games where slug = 'fc27'), 'passing', 'user', 'Fallo al centrar', 'cross_error', 1, 99, 50, 220),
  ((select id from public.games where slug = 'fc27'), 'passing', 'cpu_opponent', 'Fallo al centrar', 'cross_error', 1, 99, 50, 220),
  ((select id from public.games where slug = 'fc27'), 'passing', 'user', 'Altura del centro', 'cross_height', 1, 99, 50, 230),
  ((select id from public.games where slug = 'fc27'), 'passing', 'cpu_opponent', 'Altura del centro', 'cross_height', 1, 99, 50, 230),
  ((select id from public.games where slug = 'fc27'), 'ball_control', 'user', 'Barra de potencia', 'power_bar', 1, 99, 50, 240),
  ((select id from public.games where slug = 'fc27'), 'ball_control', 'user', 'Error de control al primer toque', 'first_touch_error', 1, 99, 50, 250),
  ((select id from public.games where slug = 'fc27'), 'ball_control', 'cpu_opponent', 'Error de control al primer toque', 'first_touch_error', 1, 99, 50, 250),
  ((select id from public.games where slug = 'fc27'), 'ball_control', 'user', 'Fallo al interceptar', 'interception_error', 1, 99, 50, 260),
  ((select id from public.games where slug = 'fc27'), 'ball_control', 'cpu_opponent', 'Fallo al interceptar', 'interception_error', 1, 99, 50, 260),
  ((select id from public.games where slug = 'fc27'), 'ball_control', 'user', 'Fallo al desviar el balón', 'deflection_error', 1, 99, 50, 270),
  ((select id from public.games where slug = 'fc27'), 'ball_control', 'cpu_opponent', 'Fallo al desviar el balón', 'deflection_error', 1, 99, 50, 270),
  ((select id from public.games where slug = 'fc27'), 'ball_control', 'user', 'Fallo al regatear al trote', 'jog_dribbling_error', 1, 99, 50, 280),
  ((select id from public.games where slug = 'fc27'), 'ball_control', 'cpu_opponent', 'Fallo al regatear al trote', 'jog_dribbling_error', 1, 99, 50, 280),
  ((select id from public.games where slug = 'fc27'), 'ball_control', 'user', 'Fallo al regatear en sprint', 'sprint_dribbling_error', 1, 99, 50, 290),
  ((select id from public.games where slug = 'fc27'), 'ball_control', 'cpu_opponent', 'Fallo al regatear en sprint', 'sprint_dribbling_error', 1, 99, 50, 290),
  ((select id from public.games where slug = 'fc27'), 'ball_control', 'user', 'Fallo al regatear en sprint controlado', 'controlled_sprint_dribbling_error', 1, 99, 50, 300),
  ((select id from public.games where slug = 'fc27'), 'ball_control', 'cpu_opponent', 'Fallo al regatear en sprint controlado', 'controlled_sprint_dribbling_error', 1, 99, 50, 300),
  ((select id from public.games where slug = 'fc27'), 'defending', 'user', 'Asistencia en entradas', 'tackle_assistance', 1, 99, 50, 310),
  ((select id from public.games where slug = 'fc27'), 'defending', 'cpu_opponent', 'Asistencia en entradas', 'tackle_assistance', 1, 99, 50, 310),
  ((select id from public.games where slug = 'fc27'), 'defending', 'user', 'Impacto físico', 'physicality_impact', 1, 99, 50, 320),
  ((select id from public.games where slug = 'fc27'), 'defending', 'cpu_opponent', 'Impacto físico', 'physicality_impact', 1, 99, 50, 320),
  ((select id from public.games where slug = 'fc27'), 'defending', 'user', 'Velocidad de contención', 'jockey_speed', 1, 99, 50, 330),
  ((select id from public.games where slug = 'fc27'), 'defending', 'cpu_opponent', 'Velocidad de contención', 'jockey_speed', 1, 99, 50, 330),
  ((select id from public.games where slug = 'fc27'), 'defending', 'user', 'Velocidad de contención en sprint', 'sprint_jockey_speed', 1, 99, 50, 340),
  ((select id from public.games where slug = 'fc27'), 'defending', 'cpu_opponent', 'Velocidad de contención en sprint', 'sprint_jockey_speed', 1, 99, 50, 340),
  ((select id from public.games where slug = 'fc27'), 'goalkeeping', 'user', 'Habilidad del guardameta', 'goalkeeper_ability', 1, 99, 50, 350),
  ((select id from public.games where slug = 'fc27'), 'goalkeeping', 'cpu_opponent', 'Habilidad del guardameta', 'goalkeeper_ability', 1, 99, 50, 350),
  ((select id from public.games where slug = 'fc27'), 'goalkeeping', 'user', 'Fallo al despejar del portero', 'gk_deflection_error', 1, 99, 50, 360),
  ((select id from public.games where slug = 'fc27'), 'goalkeeping', 'cpu_opponent', 'Fallo al despejar del portero', 'gk_deflection_error', 1, 99, 50, 360),
  ((select id from public.games where slug = 'fc27'), 'positioning', 'user', 'Marcaje', 'marking', 1, 99, 50, 370),
  ((select id from public.games where slug = 'fc27'), 'positioning', 'cpu_opponent', 'Marcaje', 'marking', 1, 99, 50, 370),
  ((select id from public.games where slug = 'fc27'), 'positioning', 'user', 'Frecuencia de desmarques', 'run_frequency', 1, 99, 50, 380),
  ((select id from public.games where slug = 'fc27'), 'positioning', 'cpu_opponent', 'Frecuencia de desmarques', 'run_frequency', 1, 99, 50, 380),
  ((select id from public.games where slug = 'fc27'), 'positioning', 'user', 'Altura de la línea', 'line_height', 1, 99, 50, 390),
  ((select id from public.games where slug = 'fc27'), 'positioning', 'cpu_opponent', 'Altura de la línea', 'line_height', 1, 99, 50, 390),
  ((select id from public.games where slug = 'fc27'), 'positioning', 'user', 'Distancia de la línea', 'line_length', 1, 99, 50, 400),
  ((select id from public.games where slug = 'fc27'), 'positioning', 'cpu_opponent', 'Distancia de la línea', 'line_length', 1, 99, 50, 400),
  ((select id from public.games where slug = 'fc27'), 'positioning', 'user', 'Ancho de la línea', 'line_width', 1, 99, 50, 410),
  ((select id from public.games where slug = 'fc27'), 'positioning', 'cpu_opponent', 'Ancho de la línea', 'line_width', 1, 99, 50, 410),
  ((select id from public.games where slug = 'fc27'), 'positioning', 'user', 'Posiciones defensivas', 'defensive_positioning', 1, 99, 50, 420),
  ((select id from public.games where slug = 'fc27'), 'positioning', 'cpu_opponent', 'Posiciones defensivas', 'defensive_positioning', 1, 99, 50, 420),
  ((select id from public.games where slug = 'fc27'), 'injuries', 'user', 'Frecuencia de lesiones', 'injury_frequency', 1, 99, 50, 430),
  ((select id from public.games where slug = 'fc27'), 'injuries', 'cpu_opponent', 'Frecuencia de lesiones', 'injury_frequency', 1, 99, 50, 430),
  ((select id from public.games where slug = 'fc27'), 'injuries', 'user', 'Gravedad de la lesión', 'injury_severity', 1, 99, 50, 440),
  ((select id from public.games where slug = 'fc27'), 'injuries', 'cpu_opponent', 'Gravedad de la lesión', 'injury_severity', 1, 99, 50, 440),
  ((select id from public.games where slug = 'fc27'), 'cpu_controls', 'cpu_opponent', 'Agresividad defensiva', 'cpu_defending_aggression', 1, 99, 50, 450),
  ((select id from public.games where slug = 'fc27'), 'cpu_controls', 'cpu_teammate', 'Agresividad defensiva', 'cpu_defending_aggression', 1, 99, 50, 450),
  ((select id from public.games where slug = 'fc27'), 'cpu_controls', 'cpu_opponent', 'Agresividad en entradas de pie', 'cpu_stand_tackle_aggression', 1, 99, 50, 460),
  ((select id from public.games where slug = 'fc27'), 'cpu_controls', 'cpu_teammate', 'Agresividad en entradas de pie', 'cpu_stand_tackle_aggression', 1, 99, 50, 460),
  ((select id from public.games where slug = 'fc27'), 'cpu_controls', 'cpu_opponent', 'Agresividad en entradas en plancha', 'cpu_slide_tackle_aggression', 1, 99, 50, 470),
  ((select id from public.games where slug = 'fc27'), 'cpu_controls', 'cpu_teammate', 'Agresividad en entradas en plancha', 'cpu_slide_tackle_aggression', 1, 99, 50, 470),
  ((select id from public.games where slug = 'fc27'), 'cpu_controls', 'cpu_opponent', 'Frecuencia de faltas tácticas', 'cpu_professional_frequency', 1, 99, 50, 480),
  ((select id from public.games where slug = 'fc27'), 'cpu_controls', 'cpu_teammate', 'Frecuencia de faltas tácticas', 'cpu_professional_frequency', 1, 99, 50, 480),
  ((select id from public.games where slug = 'fc27'), 'cpu_controls', 'cpu_opponent', 'Velocidad de creación', 'cpu_buildup_speed', 1, 99, 50, 490),
  ((select id from public.games where slug = 'fc27'), 'cpu_controls', 'cpu_teammate', 'Velocidad de creación', 'cpu_buildup_speed', 1, 99, 50, 490),
  ((select id from public.games where slug = 'fc27'), 'cpu_controls', 'cpu_opponent', 'Frecuencia de tiros', 'cpu_shot_frequency', 1, 99, 50, 500),
  ((select id from public.games where slug = 'fc27'), 'cpu_controls', 'cpu_teammate', 'Frecuencia de tiros', 'cpu_shot_frequency', 1, 99, 50, 500),
  ((select id from public.games where slug = 'fc27'), 'cpu_controls', 'cpu_opponent', 'Frecuencia de tiros por elevación', 'cpu_chip_shot_frequency', 1, 99, 50, 510),
  ((select id from public.games where slug = 'fc27'), 'cpu_controls', 'cpu_teammate', 'Frecuencia de tiros por elevación', 'cpu_chip_shot_frequency', 1, 99, 50, 510),
  ((select id from public.games where slug = 'fc27'), 'cpu_controls', 'cpu_opponent', 'Frecuencia de tiros rasos', 'cpu_low_driven_shot_frequency', 1, 99, 50, 520),
  ((select id from public.games where slug = 'fc27'), 'cpu_controls', 'cpu_teammate', 'Frecuencia de tiros rasos', 'cpu_low_driven_shot_frequency', 1, 99, 50, 520),
  ((select id from public.games where slug = 'fc27'), 'cpu_controls', 'cpu_opponent', 'Frecuencia de tiros colocados', 'cpu_finesse_shot_frequency', 1, 99, 50, 530),
  ((select id from public.games where slug = 'fc27'), 'cpu_controls', 'cpu_teammate', 'Frecuencia de tiros colocados', 'cpu_finesse_shot_frequency', 1, 99, 50, 530),
  ((select id from public.games where slug = 'fc27'), 'cpu_controls', 'cpu_opponent', 'Frecuencia de tiros lejanos', 'cpu_long_shot_frequency', 1, 99, 50, 540),
  ((select id from public.games where slug = 'fc27'), 'cpu_controls', 'cpu_teammate', 'Frecuencia de tiros lejanos', 'cpu_long_shot_frequency', 1, 99, 50, 540),
  ((select id from public.games where slug = 'fc27'), 'cpu_controls', 'cpu_opponent', 'Frecuencia de disparos potentes', 'cpu_power_shot_frequency', 1, 99, 50, 550),
  ((select id from public.games where slug = 'fc27'), 'cpu_controls', 'cpu_teammate', 'Frecuencia de disparos potentes', 'cpu_power_shot_frequency', 1, 99, 50, 550),
  ((select id from public.games where slug = 'fc27'), 'cpu_controls', 'cpu_opponent', 'Frecuencia de pases al primer toque', 'cpu_first_touch_pass_frequency', 1, 99, 50, 560),
  ((select id from public.games where slug = 'fc27'), 'cpu_controls', 'cpu_teammate', 'Frecuencia de pases al primer toque', 'cpu_first_touch_pass_frequency', 1, 99, 50, 560),
  ((select id from public.games where slug = 'fc27'), 'cpu_controls', 'cpu_opponent', 'Frecuencia de centros', 'cpu_cross_frequency', 1, 99, 50, 570),
  ((select id from public.games where slug = 'fc27'), 'cpu_controls', 'cpu_teammate', 'Frecuencia de centros', 'cpu_cross_frequency', 1, 99, 50, 570),
  ((select id from public.games where slug = 'fc27'), 'cpu_controls', 'cpu_opponent', 'Frecuencia de centros tempranos', 'cpu_early_cross_frequency', 1, 99, 50, 580),
  ((select id from public.games where slug = 'fc27'), 'cpu_controls', 'cpu_teammate', 'Frecuencia de centros tempranos', 'cpu_early_cross_frequency', 1, 99, 50, 580),
  ((select id from public.games where slug = 'fc27'), 'cpu_controls', 'cpu_opponent', 'Frecuencia de regates', 'cpu_dribble_frequency', 1, 99, 50, 590),
  ((select id from public.games where slug = 'fc27'), 'cpu_controls', 'cpu_teammate', 'Frecuencia de regates', 'cpu_dribble_frequency', 1, 99, 50, 590),
  ((select id from public.games where slug = 'fc27'), 'cpu_controls', 'cpu_opponent', 'Frecuencia de filigranas', 'cpu_skill_move_frequency', 1, 99, 50, 600),
  ((select id from public.games where slug = 'fc27'), 'cpu_controls', 'cpu_teammate', 'Frecuencia de filigranas', 'cpu_skill_move_frequency', 1, 99, 50, 600),
  ((select id from public.games where slug = 'fc26'), 'speed', 'user', 'Velocidad', 'sprint_speed', 0, 100, 50, 0),
  ((select id from public.games where slug = 'fc26'), 'speed', 'cpu', 'Velocidad', 'sprint_speed', 0, 100, 50, 0),
  ((select id from public.games where slug = 'fc26'), 'speed', 'user', 'Aceleración', 'acceleration', 0, 100, 50, 10),
  ((select id from public.games where slug = 'fc26'), 'speed', 'cpu', 'Aceleración', 'acceleration', 0, 100, 50, 10),
  ((select id from public.games where slug = 'fc26'), 'shooting', 'user', 'Fallo al tirar', 'shot_error', 0, 100, 50, 20),
  ((select id from public.games where slug = 'fc26'), 'shooting', 'cpu', 'Fallo al tirar', 'shot_error', 0, 100, 50, 20),
  ((select id from public.games where slug = 'fc26'), 'shooting', 'user', 'Velocidad de tiro', 'shot_speed', 0, 100, 50, 30),
  ((select id from public.games where slug = 'fc26'), 'shooting', 'cpu', 'Velocidad de tiro', 'shot_speed', 0, 100, 50, 30),
  ((select id from public.games where slug = 'fc26'), 'shooting', 'user', 'Fallo al rematar de cabeza', 'header_shot_error', 0, 100, 50, 40),
  ((select id from public.games where slug = 'fc26'), 'shooting', 'cpu', 'Fallo al rematar de cabeza', 'header_shot_error', 0, 100, 50, 40),
  ((select id from public.games where slug = 'fc26'), 'passing', 'user', 'Fallo al pasar', 'pass_error', 0, 100, 50, 50),
  ((select id from public.games where slug = 'fc26'), 'passing', 'cpu', 'Fallo al pasar', 'pass_error', 0, 100, 50, 50),
  ((select id from public.games where slug = 'fc26'), 'passing', 'user', 'Velocidad del pase', 'pass_speed', 0, 100, 50, 60),
  ((select id from public.games where slug = 'fc26'), 'passing', 'cpu', 'Velocidad del pase', 'pass_speed', 0, 100, 50, 60),
  ((select id from public.games where slug = 'fc26'), 'passing', 'user', 'Fallo al pasar de cabeza', 'header_pass_error', 0, 100, 50, 70),
  ((select id from public.games where slug = 'fc26'), 'passing', 'cpu', 'Fallo al pasar de cabeza', 'header_pass_error', 0, 100, 50, 70),
  ((select id from public.games where slug = 'fc26'), 'ball_control', 'user', 'Barra de potencia', 'power_bar', 0, 100, 50, 80),
  ((select id from public.games where slug = 'fc26'), 'ball_control', 'user', 'Error de control al primer toque', 'first_touch_error', 0, 100, 50, 90),
  ((select id from public.games where slug = 'fc26'), 'ball_control', 'cpu', 'Error de control al primer toque', 'first_touch_error', 0, 100, 50, 90),
  ((select id from public.games where slug = 'fc26'), 'ball_control', 'user', 'Fallo al interceptar', 'interception_error', 0, 100, 50, 100),
  ((select id from public.games where slug = 'fc26'), 'ball_control', 'cpu', 'Fallo al interceptar', 'interception_error', 0, 100, 50, 100),
  ((select id from public.games where slug = 'fc26'), 'ball_control', 'user', 'Fallo al desviar el balón', 'deflection_error', 0, 100, 50, 110),
  ((select id from public.games where slug = 'fc26'), 'ball_control', 'cpu', 'Fallo al desviar el balón', 'deflection_error', 0, 100, 50, 110),
  ((select id from public.games where slug = 'fc26'), 'defending', 'user', 'Asistencia en entradas', 'tackle_assistance', 0, 100, 50, 120),
  ((select id from public.games where slug = 'fc26'), 'defending', 'cpu', 'Asistencia en entradas', 'tackle_assistance', 0, 100, 50, 120),
  ((select id from public.games where slug = 'fc26'), 'goalkeeping', 'user', 'Habilidad del guardameta', 'goalkeeper_ability', 0, 100, 50, 130),
  ((select id from public.games where slug = 'fc26'), 'goalkeeping', 'cpu', 'Habilidad del guardameta', 'goalkeeper_ability', 0, 100, 50, 130),
  ((select id from public.games where slug = 'fc26'), 'positioning', 'user', 'Marcaje', 'marking', 0, 100, 50, 140),
  ((select id from public.games where slug = 'fc26'), 'positioning', 'cpu', 'Marcaje', 'marking', 0, 100, 50, 140),
  ((select id from public.games where slug = 'fc26'), 'positioning', 'user', 'Frecuencia de desmarques', 'run_frequency', 0, 100, 50, 150),
  ((select id from public.games where slug = 'fc26'), 'positioning', 'cpu', 'Frecuencia de desmarques', 'run_frequency', 0, 100, 50, 150),
  ((select id from public.games where slug = 'fc26'), 'positioning', 'user', 'Altura de la línea', 'line_height', 0, 100, 50, 160),
  ((select id from public.games where slug = 'fc26'), 'positioning', 'cpu', 'Altura de la línea', 'line_height', 0, 100, 50, 160),
  ((select id from public.games where slug = 'fc26'), 'positioning', 'user', 'Distancia de la línea', 'line_length', 0, 100, 50, 170),
  ((select id from public.games where slug = 'fc26'), 'positioning', 'cpu', 'Distancia de la línea', 'line_length', 0, 100, 50, 170),
  ((select id from public.games where slug = 'fc26'), 'positioning', 'user', 'Ancho de la línea', 'line_width', 0, 100, 50, 180),
  ((select id from public.games where slug = 'fc26'), 'positioning', 'cpu', 'Ancho de la línea', 'line_width', 0, 100, 50, 180),
  ((select id from public.games where slug = 'fc26'), 'positioning', 'user', 'Posiciones defensivas', 'defensive_positioning', 0, 100, 50, 190),
  ((select id from public.games where slug = 'fc26'), 'positioning', 'cpu', 'Posiciones defensivas', 'defensive_positioning', 0, 100, 50, 190),
  ((select id from public.games where slug = 'fc26'), 'injuries', 'user', 'Frecuencia de lesiones', 'injury_frequency', 0, 100, 50, 200),
  ((select id from public.games where slug = 'fc26'), 'injuries', 'cpu', 'Frecuencia de lesiones', 'injury_frequency', 0, 100, 50, 200),
  ((select id from public.games where slug = 'fc26'), 'injuries', 'user', 'Gravedad de la lesión', 'injury_severity', 0, 100, 50, 210),
  ((select id from public.games where slug = 'fc26'), 'injuries', 'cpu', 'Gravedad de la lesión', 'injury_severity', 0, 100, 50, 210),
  ((select id from public.games where slug = 'fc26'), 'cpu_controls', 'cpu', 'Agresividad en las entradas', 'cpu_tackle_aggression', 0, 100, 50, 220),
  ((select id from public.games where slug = 'fc26'), 'cpu_controls', 'cpu', 'Velocidad de creación', 'cpu_buildup_speed', 0, 100, 50, 230),
  ((select id from public.games where slug = 'fc26'), 'cpu_controls', 'cpu', 'Frecuencia de tiros', 'cpu_shot_frequency', 0, 100, 50, 240),
  ((select id from public.games where slug = 'fc26'), 'cpu_controls', 'cpu', 'Frecuencia de pases al primer toque', 'cpu_first_touch_pass_frequency', 0, 100, 50, 250),
  ((select id from public.games where slug = 'fc26'), 'cpu_controls', 'cpu', 'Frecuencia de centros', 'cpu_cross_frequency', 0, 100, 50, 260),
  ((select id from public.games where slug = 'fc26'), 'cpu_controls', 'cpu', 'Frecuencia de regates', 'cpu_dribble_frequency', 0, 100, 50, 270),
  ((select id from public.games where slug = 'fc26'), 'cpu_controls', 'cpu', 'Frecuencia de filigranas', 'cpu_flair_frequency', 0, 100, 50, 280)
on conflict (game_id, slug, applies_to) do update
  set category      = excluded.category,
      name          = excluded.name,
      min_value     = excluded.min_value,
      max_value     = excluded.max_value,
      default_value = excluded.default_value,
      sort_order    = excluded.sort_order;

-- Limpieza: lo que ya no está en el catálogo -------------------------------
delete from public.slider_definitions
where game_id = (select id from public.games where slug = 'fc27')
  and slug not in ('sprint_speed', 'acceleration', 'shot_error', 'shot_speed', 'finesse_shot_error', 'finesse_shot_speed', 'chip_shot_error', 'chip_shot_speed', 'low_driven_shot_error', 'low_driven_shot_speed', 'power_shot_error', 'power_shot_speed', 'header_shot_error', 'pass_error', 'pass_speed', 'header_pass_error', 'through_pass_error', 'through_pass_speed', 'lobbed_through_pass_error', 'lobbed_through_pass_speed', 'lob_pass_error', 'lob_pass_speed', 'cross_error', 'cross_height', 'power_bar', 'first_touch_error', 'interception_error', 'deflection_error', 'jog_dribbling_error', 'sprint_dribbling_error', 'controlled_sprint_dribbling_error', 'tackle_assistance', 'physicality_impact', 'jockey_speed', 'sprint_jockey_speed', 'goalkeeper_ability', 'gk_deflection_error', 'marking', 'run_frequency', 'line_height', 'line_length', 'line_width', 'defensive_positioning', 'injury_frequency', 'injury_severity', 'cpu_defending_aggression', 'cpu_stand_tackle_aggression', 'cpu_slide_tackle_aggression', 'cpu_professional_frequency', 'cpu_buildup_speed', 'cpu_shot_frequency', 'cpu_chip_shot_frequency', 'cpu_low_driven_shot_frequency', 'cpu_finesse_shot_frequency', 'cpu_long_shot_frequency', 'cpu_power_shot_frequency', 'cpu_first_touch_pass_frequency', 'cpu_cross_frequency', 'cpu_early_cross_frequency', 'cpu_dribble_frequency', 'cpu_skill_move_frequency');

delete from public.slider_definitions
where game_id = (select id from public.games where slug = 'fc26')
  and slug not in ('sprint_speed', 'acceleration', 'shot_error', 'shot_speed', 'header_shot_error', 'pass_error', 'pass_speed', 'header_pass_error', 'power_bar', 'first_touch_error', 'interception_error', 'deflection_error', 'tackle_assistance', 'goalkeeper_ability', 'marking', 'run_frequency', 'line_height', 'line_length', 'line_width', 'defensive_positioning', 'injury_frequency', 'injury_severity', 'cpu_tackle_aggression', 'cpu_buildup_speed', 'cpu_shot_frequency', 'cpu_first_touch_pass_frequency', 'cpu_cross_frequency', 'cpu_dribble_frequency', 'cpu_flair_frequency');

commit;
