-- GENERADO POR scripts/build-seed.mjs — no editar a mano.
-- Editar supabase/seed/catalog.mjs y ejecutar `npm run seed:build`.

begin;

-- Juegos ------------------------------------------------------------------
insert into public.games (slug, name, release_year) values
  ('fc27', 'EA SPORTS FC 27', 2026),
  ('fc26', 'EA SPORTS FC 26', 2025)
on conflict (slug) do update
  set name = excluded.name, release_year = excluded.release_year;

-- Sliders -----------------------------------------------------------------
insert into public.slider_definitions
  (game_id, category, applies_to, name, slug, min_value, max_value, default_value, sort_order)
values
  ((select id from public.games where slug = 'fc27'), 'speed', 'user', 'Velocidad', 'sprint_speed', 0, 100, 50, 0),
  ((select id from public.games where slug = 'fc27'), 'speed', 'cpu_opponent', 'Velocidad', 'sprint_speed', 0, 100, 50, 0),
  ((select id from public.games where slug = 'fc27'), 'speed', 'cpu_teammate', 'Velocidad', 'sprint_speed', 0, 100, 50, 0),
  ((select id from public.games where slug = 'fc27'), 'speed', 'user', 'Aceleración', 'acceleration', 0, 100, 50, 10),
  ((select id from public.games where slug = 'fc27'), 'speed', 'cpu_opponent', 'Aceleración', 'acceleration', 0, 100, 50, 10),
  ((select id from public.games where slug = 'fc27'), 'speed', 'cpu_teammate', 'Aceleración', 'acceleration', 0, 100, 50, 10),
  ((select id from public.games where slug = 'fc27'), 'shooting', 'user', 'Fallo al tirar', 'shot_error', 0, 100, 50, 20),
  ((select id from public.games where slug = 'fc27'), 'shooting', 'cpu_opponent', 'Fallo al tirar', 'shot_error', 0, 100, 50, 20),
  ((select id from public.games where slug = 'fc27'), 'shooting', 'cpu_teammate', 'Fallo al tirar', 'shot_error', 0, 100, 50, 20),
  ((select id from public.games where slug = 'fc27'), 'shooting', 'user', 'Velocidad de tiro', 'shot_speed', 0, 100, 50, 30),
  ((select id from public.games where slug = 'fc27'), 'shooting', 'cpu_opponent', 'Velocidad de tiro', 'shot_speed', 0, 100, 50, 30),
  ((select id from public.games where slug = 'fc27'), 'shooting', 'cpu_teammate', 'Velocidad de tiro', 'shot_speed', 0, 100, 50, 30),
  ((select id from public.games where slug = 'fc27'), 'shooting', 'user', 'Fallo al rematar de cabeza', 'header_shot_error', 0, 100, 50, 40),
  ((select id from public.games where slug = 'fc27'), 'shooting', 'cpu_opponent', 'Fallo al rematar de cabeza', 'header_shot_error', 0, 100, 50, 40),
  ((select id from public.games where slug = 'fc27'), 'shooting', 'cpu_teammate', 'Fallo al rematar de cabeza', 'header_shot_error', 0, 100, 50, 40),
  ((select id from public.games where slug = 'fc27'), 'passing', 'user', 'Fallo al pasar', 'pass_error', 0, 100, 50, 50),
  ((select id from public.games where slug = 'fc27'), 'passing', 'cpu_opponent', 'Fallo al pasar', 'pass_error', 0, 100, 50, 50),
  ((select id from public.games where slug = 'fc27'), 'passing', 'cpu_teammate', 'Fallo al pasar', 'pass_error', 0, 100, 50, 50),
  ((select id from public.games where slug = 'fc27'), 'passing', 'user', 'Velocidad del pase', 'pass_speed', 0, 100, 50, 60),
  ((select id from public.games where slug = 'fc27'), 'passing', 'cpu_opponent', 'Velocidad del pase', 'pass_speed', 0, 100, 50, 60),
  ((select id from public.games where slug = 'fc27'), 'passing', 'cpu_teammate', 'Velocidad del pase', 'pass_speed', 0, 100, 50, 60),
  ((select id from public.games where slug = 'fc27'), 'passing', 'user', 'Fallo al pasar de cabeza', 'header_pass_error', 0, 100, 50, 70),
  ((select id from public.games where slug = 'fc27'), 'passing', 'cpu_opponent', 'Fallo al pasar de cabeza', 'header_pass_error', 0, 100, 50, 70),
  ((select id from public.games where slug = 'fc27'), 'passing', 'cpu_teammate', 'Fallo al pasar de cabeza', 'header_pass_error', 0, 100, 50, 70),
  ((select id from public.games where slug = 'fc27'), 'ball_control', 'user', 'Barra de potencia', 'power_bar', 0, 100, 50, 80),
  ((select id from public.games where slug = 'fc27'), 'ball_control', 'user', 'Error de control al primer toque', 'first_touch_error', 0, 100, 50, 90),
  ((select id from public.games where slug = 'fc27'), 'ball_control', 'cpu_opponent', 'Error de control al primer toque', 'first_touch_error', 0, 100, 50, 90),
  ((select id from public.games where slug = 'fc27'), 'ball_control', 'cpu_teammate', 'Error de control al primer toque', 'first_touch_error', 0, 100, 50, 90),
  ((select id from public.games where slug = 'fc27'), 'ball_control', 'user', 'Fallo al interceptar', 'interception_error', 0, 100, 50, 100),
  ((select id from public.games where slug = 'fc27'), 'ball_control', 'cpu_opponent', 'Fallo al interceptar', 'interception_error', 0, 100, 50, 100),
  ((select id from public.games where slug = 'fc27'), 'ball_control', 'cpu_teammate', 'Fallo al interceptar', 'interception_error', 0, 100, 50, 100),
  ((select id from public.games where slug = 'fc27'), 'ball_control', 'user', 'Fallo al desviar el balón', 'deflection_error', 0, 100, 50, 110),
  ((select id from public.games where slug = 'fc27'), 'ball_control', 'cpu_opponent', 'Fallo al desviar el balón', 'deflection_error', 0, 100, 50, 110),
  ((select id from public.games where slug = 'fc27'), 'ball_control', 'cpu_teammate', 'Fallo al desviar el balón', 'deflection_error', 0, 100, 50, 110),
  ((select id from public.games where slug = 'fc27'), 'defending', 'user', 'Asistencia en entradas', 'tackle_assistance', 0, 100, 50, 120),
  ((select id from public.games where slug = 'fc27'), 'defending', 'cpu_opponent', 'Asistencia en entradas', 'tackle_assistance', 0, 100, 50, 120),
  ((select id from public.games where slug = 'fc27'), 'defending', 'cpu_teammate', 'Asistencia en entradas', 'tackle_assistance', 0, 100, 50, 120),
  ((select id from public.games where slug = 'fc27'), 'goalkeeping', 'user', 'Habilidad del guardameta', 'goalkeeper_ability', 0, 100, 50, 130),
  ((select id from public.games where slug = 'fc27'), 'goalkeeping', 'cpu_opponent', 'Habilidad del guardameta', 'goalkeeper_ability', 0, 100, 50, 130),
  ((select id from public.games where slug = 'fc27'), 'goalkeeping', 'cpu_teammate', 'Habilidad del guardameta', 'goalkeeper_ability', 0, 100, 50, 130),
  ((select id from public.games where slug = 'fc27'), 'positioning', 'user', 'Marcaje', 'marking', 0, 100, 50, 140),
  ((select id from public.games where slug = 'fc27'), 'positioning', 'cpu_opponent', 'Marcaje', 'marking', 0, 100, 50, 140),
  ((select id from public.games where slug = 'fc27'), 'positioning', 'cpu_teammate', 'Marcaje', 'marking', 0, 100, 50, 140),
  ((select id from public.games where slug = 'fc27'), 'positioning', 'user', 'Frecuencia de desmarques', 'run_frequency', 0, 100, 50, 150),
  ((select id from public.games where slug = 'fc27'), 'positioning', 'cpu_opponent', 'Frecuencia de desmarques', 'run_frequency', 0, 100, 50, 150),
  ((select id from public.games where slug = 'fc27'), 'positioning', 'cpu_teammate', 'Frecuencia de desmarques', 'run_frequency', 0, 100, 50, 150),
  ((select id from public.games where slug = 'fc27'), 'positioning', 'user', 'Altura de la línea', 'line_height', 0, 100, 50, 160),
  ((select id from public.games where slug = 'fc27'), 'positioning', 'cpu_opponent', 'Altura de la línea', 'line_height', 0, 100, 50, 160),
  ((select id from public.games where slug = 'fc27'), 'positioning', 'cpu_teammate', 'Altura de la línea', 'line_height', 0, 100, 50, 160),
  ((select id from public.games where slug = 'fc27'), 'positioning', 'user', 'Distancia de la línea', 'line_length', 0, 100, 50, 170),
  ((select id from public.games where slug = 'fc27'), 'positioning', 'cpu_opponent', 'Distancia de la línea', 'line_length', 0, 100, 50, 170),
  ((select id from public.games where slug = 'fc27'), 'positioning', 'cpu_teammate', 'Distancia de la línea', 'line_length', 0, 100, 50, 170),
  ((select id from public.games where slug = 'fc27'), 'positioning', 'user', 'Ancho de la línea', 'line_width', 0, 100, 50, 180),
  ((select id from public.games where slug = 'fc27'), 'positioning', 'cpu_opponent', 'Ancho de la línea', 'line_width', 0, 100, 50, 180),
  ((select id from public.games where slug = 'fc27'), 'positioning', 'cpu_teammate', 'Ancho de la línea', 'line_width', 0, 100, 50, 180),
  ((select id from public.games where slug = 'fc27'), 'positioning', 'user', 'Posiciones defensivas', 'defensive_positioning', 0, 100, 50, 190),
  ((select id from public.games where slug = 'fc27'), 'positioning', 'cpu_opponent', 'Posiciones defensivas', 'defensive_positioning', 0, 100, 50, 190),
  ((select id from public.games where slug = 'fc27'), 'positioning', 'cpu_teammate', 'Posiciones defensivas', 'defensive_positioning', 0, 100, 50, 190),
  ((select id from public.games where slug = 'fc27'), 'injuries', 'user', 'Frecuencia de lesiones', 'injury_frequency', 0, 100, 50, 200),
  ((select id from public.games where slug = 'fc27'), 'injuries', 'cpu_opponent', 'Frecuencia de lesiones', 'injury_frequency', 0, 100, 50, 200),
  ((select id from public.games where slug = 'fc27'), 'injuries', 'cpu_teammate', 'Frecuencia de lesiones', 'injury_frequency', 0, 100, 50, 200),
  ((select id from public.games where slug = 'fc27'), 'injuries', 'user', 'Gravedad de la lesión', 'injury_severity', 0, 100, 50, 210),
  ((select id from public.games where slug = 'fc27'), 'injuries', 'cpu_opponent', 'Gravedad de la lesión', 'injury_severity', 0, 100, 50, 210),
  ((select id from public.games where slug = 'fc27'), 'injuries', 'cpu_teammate', 'Gravedad de la lesión', 'injury_severity', 0, 100, 50, 210),
  ((select id from public.games where slug = 'fc27'), 'cpu_controls', 'cpu_opponent', 'Agresividad en las entradas', 'cpu_tackle_aggression', 0, 100, 50, 220),
  ((select id from public.games where slug = 'fc27'), 'cpu_controls', 'cpu_opponent', 'Velocidad de creación', 'cpu_buildup_speed', 0, 100, 50, 230),
  ((select id from public.games where slug = 'fc27'), 'cpu_controls', 'cpu_opponent', 'Frecuencia de tiros', 'cpu_shot_frequency', 0, 100, 50, 240),
  ((select id from public.games where slug = 'fc27'), 'cpu_controls', 'cpu_opponent', 'Frecuencia de pases al primer toque', 'cpu_first_touch_pass_frequency', 0, 100, 50, 250),
  ((select id from public.games where slug = 'fc27'), 'cpu_controls', 'cpu_opponent', 'Frecuencia de centros', 'cpu_cross_frequency', 0, 100, 50, 260),
  ((select id from public.games where slug = 'fc27'), 'cpu_controls', 'cpu_opponent', 'Frecuencia de regates', 'cpu_dribble_frequency', 0, 100, 50, 270),
  ((select id from public.games where slug = 'fc27'), 'cpu_controls', 'cpu_opponent', 'Frecuencia de filigranas', 'cpu_flair_frequency', 0, 100, 50, 280),
  ((select id from public.games where slug = 'fc26'), 'speed', 'user', 'Velocidad', 'sprint_speed', 0, 100, 50, 0),
  ((select id from public.games where slug = 'fc26'), 'speed', 'cpu', 'Velocidad', 'sprint_speed', 0, 100, 50, 0),
  ((select id from public.games where slug = 'fc26'), 'speed', 'user', 'Aceleración', 'acceleration', 0, 100, 50, 10),
  ((select id from public.games where slug = 'fc26'), 'speed', 'cpu', 'Aceleración', 'acceleration', 0, 100, 50, 10),
  ((select id from public.games where slug = 'fc26'), 'shooting', 'user', 'Fallo al tirar', 'shot_error', 0, 100, 50, 20),
  ((select id from public.games where slug = 'fc26'), 'shooting', 'cpu', 'Fallo al tirar', 'shot_error', 0, 100, 50, 20),
  ((select id from public.games where slug = 'fc26'), 'shooting', 'user', 'Velocidad de tiro', 'shot_speed', 0, 100, 50, 30),
  ((select id from public.games where slug = 'fc26'), 'shooting', 'cpu', 'Velocidad de tiro', 'shot_speed', 0, 100, 50, 30),
  ((select id from public.games where slug = 'fc26'), 'shooting', 'user', 'Fallo al rematar de cabeza', 'header_shot_error', 0, 100, 50, 40),
  ((select id from public.games where slug = 'fc26'), 'shooting', 'cpu', 'Fallo al rematar de cabeza', 'header_shot_error', 0, 100, 50, 40),
  ((select id from public.games where slug = 'fc26'), 'passing', 'user', 'Fallo al pasar', 'pass_error', 0, 100, 50, 50),
  ((select id from public.games where slug = 'fc26'), 'passing', 'cpu', 'Fallo al pasar', 'pass_error', 0, 100, 50, 50),
  ((select id from public.games where slug = 'fc26'), 'passing', 'user', 'Velocidad del pase', 'pass_speed', 0, 100, 50, 60),
  ((select id from public.games where slug = 'fc26'), 'passing', 'cpu', 'Velocidad del pase', 'pass_speed', 0, 100, 50, 60),
  ((select id from public.games where slug = 'fc26'), 'passing', 'user', 'Fallo al pasar de cabeza', 'header_pass_error', 0, 100, 50, 70),
  ((select id from public.games where slug = 'fc26'), 'passing', 'cpu', 'Fallo al pasar de cabeza', 'header_pass_error', 0, 100, 50, 70),
  ((select id from public.games where slug = 'fc26'), 'ball_control', 'user', 'Barra de potencia', 'power_bar', 0, 100, 50, 80),
  ((select id from public.games where slug = 'fc26'), 'ball_control', 'user', 'Error de control al primer toque', 'first_touch_error', 0, 100, 50, 90),
  ((select id from public.games where slug = 'fc26'), 'ball_control', 'cpu', 'Error de control al primer toque', 'first_touch_error', 0, 100, 50, 90),
  ((select id from public.games where slug = 'fc26'), 'ball_control', 'user', 'Fallo al interceptar', 'interception_error', 0, 100, 50, 100),
  ((select id from public.games where slug = 'fc26'), 'ball_control', 'cpu', 'Fallo al interceptar', 'interception_error', 0, 100, 50, 100),
  ((select id from public.games where slug = 'fc26'), 'ball_control', 'user', 'Fallo al desviar el balón', 'deflection_error', 0, 100, 50, 110),
  ((select id from public.games where slug = 'fc26'), 'ball_control', 'cpu', 'Fallo al desviar el balón', 'deflection_error', 0, 100, 50, 110),
  ((select id from public.games where slug = 'fc26'), 'defending', 'user', 'Asistencia en entradas', 'tackle_assistance', 0, 100, 50, 120),
  ((select id from public.games where slug = 'fc26'), 'defending', 'cpu', 'Asistencia en entradas', 'tackle_assistance', 0, 100, 50, 120),
  ((select id from public.games where slug = 'fc26'), 'goalkeeping', 'user', 'Habilidad del guardameta', 'goalkeeper_ability', 0, 100, 50, 130),
  ((select id from public.games where slug = 'fc26'), 'goalkeeping', 'cpu', 'Habilidad del guardameta', 'goalkeeper_ability', 0, 100, 50, 130),
  ((select id from public.games where slug = 'fc26'), 'positioning', 'user', 'Marcaje', 'marking', 0, 100, 50, 140),
  ((select id from public.games where slug = 'fc26'), 'positioning', 'cpu', 'Marcaje', 'marking', 0, 100, 50, 140),
  ((select id from public.games where slug = 'fc26'), 'positioning', 'user', 'Frecuencia de desmarques', 'run_frequency', 0, 100, 50, 150),
  ((select id from public.games where slug = 'fc26'), 'positioning', 'cpu', 'Frecuencia de desmarques', 'run_frequency', 0, 100, 50, 150),
  ((select id from public.games where slug = 'fc26'), 'positioning', 'user', 'Altura de la línea', 'line_height', 0, 100, 50, 160),
  ((select id from public.games where slug = 'fc26'), 'positioning', 'cpu', 'Altura de la línea', 'line_height', 0, 100, 50, 160),
  ((select id from public.games where slug = 'fc26'), 'positioning', 'user', 'Distancia de la línea', 'line_length', 0, 100, 50, 170),
  ((select id from public.games where slug = 'fc26'), 'positioning', 'cpu', 'Distancia de la línea', 'line_length', 0, 100, 50, 170),
  ((select id from public.games where slug = 'fc26'), 'positioning', 'user', 'Ancho de la línea', 'line_width', 0, 100, 50, 180),
  ((select id from public.games where slug = 'fc26'), 'positioning', 'cpu', 'Ancho de la línea', 'line_width', 0, 100, 50, 180),
  ((select id from public.games where slug = 'fc26'), 'positioning', 'user', 'Posiciones defensivas', 'defensive_positioning', 0, 100, 50, 190),
  ((select id from public.games where slug = 'fc26'), 'positioning', 'cpu', 'Posiciones defensivas', 'defensive_positioning', 0, 100, 50, 190),
  ((select id from public.games where slug = 'fc26'), 'injuries', 'user', 'Frecuencia de lesiones', 'injury_frequency', 0, 100, 50, 200),
  ((select id from public.games where slug = 'fc26'), 'injuries', 'cpu', 'Frecuencia de lesiones', 'injury_frequency', 0, 100, 50, 200),
  ((select id from public.games where slug = 'fc26'), 'injuries', 'user', 'Gravedad de la lesión', 'injury_severity', 0, 100, 50, 210),
  ((select id from public.games where slug = 'fc26'), 'injuries', 'cpu', 'Gravedad de la lesión', 'injury_severity', 0, 100, 50, 210),
  ((select id from public.games where slug = 'fc26'), 'cpu_controls', 'cpu', 'Agresividad en las entradas', 'cpu_tackle_aggression', 0, 100, 50, 220),
  ((select id from public.games where slug = 'fc26'), 'cpu_controls', 'cpu', 'Velocidad de creación', 'cpu_buildup_speed', 0, 100, 50, 230),
  ((select id from public.games where slug = 'fc26'), 'cpu_controls', 'cpu', 'Frecuencia de tiros', 'cpu_shot_frequency', 0, 100, 50, 240),
  ((select id from public.games where slug = 'fc26'), 'cpu_controls', 'cpu', 'Frecuencia de pases al primer toque', 'cpu_first_touch_pass_frequency', 0, 100, 50, 250),
  ((select id from public.games where slug = 'fc26'), 'cpu_controls', 'cpu', 'Frecuencia de centros', 'cpu_cross_frequency', 0, 100, 50, 260),
  ((select id from public.games where slug = 'fc26'), 'cpu_controls', 'cpu', 'Frecuencia de regates', 'cpu_dribble_frequency', 0, 100, 50, 270),
  ((select id from public.games where slug = 'fc26'), 'cpu_controls', 'cpu', 'Frecuencia de filigranas', 'cpu_flair_frequency', 0, 100, 50, 280)
on conflict (game_id, slug, applies_to) do update
  set category      = excluded.category,
      name          = excluded.name,
      min_value     = excluded.min_value,
      max_value     = excluded.max_value,
      default_value = excluded.default_value,
      sort_order    = excluded.sort_order;

-- Limpieza de sliders que ya no están en el catálogo ---------------------
delete from public.slider_definitions
where game_id = (select id from public.games where slug = 'fc27')
  and slug not in ('sprint_speed', 'acceleration', 'shot_error', 'shot_speed', 'header_shot_error', 'pass_error', 'pass_speed', 'header_pass_error', 'power_bar', 'first_touch_error', 'interception_error', 'deflection_error', 'tackle_assistance', 'goalkeeper_ability', 'marking', 'run_frequency', 'line_height', 'line_length', 'line_width', 'defensive_positioning', 'injury_frequency', 'injury_severity', 'cpu_tackle_aggression', 'cpu_buildup_speed', 'cpu_shot_frequency', 'cpu_first_touch_pass_frequency', 'cpu_cross_frequency', 'cpu_dribble_frequency', 'cpu_flair_frequency');

delete from public.slider_definitions
where game_id = (select id from public.games where slug = 'fc26')
  and slug not in ('sprint_speed', 'acceleration', 'shot_error', 'shot_speed', 'header_shot_error', 'pass_error', 'pass_speed', 'header_pass_error', 'power_bar', 'first_touch_error', 'interception_error', 'deflection_error', 'tackle_assistance', 'goalkeeper_ability', 'marking', 'run_frequency', 'line_height', 'line_length', 'line_width', 'defensive_positioning', 'injury_frequency', 'injury_severity', 'cpu_tackle_aggression', 'cpu_buildup_speed', 'cpu_shot_frequency', 'cpu_first_touch_pass_frequency', 'cpu_cross_frequency', 'cpu_dribble_frequency', 'cpu_flair_frequency');

commit;
